name: Year Progress
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # This schedules the workflow to run at midnight UTC every day
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Build
        run: cargo build --release

      - name: Run year progress
        run: ./target/release/year

      - name: Commit change & Push
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          timestamp=$(date -u +"%Y-%m-%d %H:%M:%S UTC")
          git commit -m "bot: update README on $timestamp"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}