name: Year Progress
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1'  # This schedules the workflow to run at midnight UTC every day
jobs:
  build:
    runs-on: ubuntu-latest
    # Give the default GITHUB_TOKEN write permission to commit and push the
    # added or changed files to the repository.
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable  
      - name: Build
        run: cargo build --release
      - name: Run year progress
        run: ./target/release/year
      - name: Commit change & Push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Skip[bot]: Update README.md"
          commit_user_name: "duynhbot"
          commit_user_email: "duynhbot@users.noreply.github.com"
          file_pattern: '*.md'
          skip_dirty_check: true
